version: '3.8'
services:
  api:
    build: .
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
