version: '3.8'
services:
  api:
    build: .
    ports:
      - "5133:5133"
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=kwiz_password
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
